<!DOCTYPE html>

<html lang="en">
<head>
	<!-- Required meta tags -->
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<!-- Bootstrap CSS -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
	<link rel="stylesheet" href="css/styles.css" type="text/css">
	<link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet">
	<title>Mi Patio Mexican Restaurant</title>
</head>
<body>
	
    <?php include("includes/header.php"); ?>
    
	<!-- Center of the Page-->
	<div class="menu-pages">
		<h1>Appetizers</h1>
			<div class="row">
				<div class="col-lg-4">
					<p class="menu-item" >Spin N Art Dip</p>
					<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Mi tempus imperdiet nulla malesuada pellentesque elit eget.</p>
					<p>$7.15</p>
				</div>
				<div class="col-lg-4">
					<p class="menu-item" >Cheezie-Bean Dip</p>
					<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Mi tempus imperdiet nulla malesuada pellentesque elit eget.</p>
					<p>$6.00</p>
				</div>
				<div class="col-lg-4">
					<p class="menu-item" >Cheese Dip</p>
					<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Mi tempus imperdiet nulla malesuada pellentesque elit eget.</p>
					<p>Small $3.90 - Large $7.10</p>
				</div>
			</div>
			<div class="row">
				<div class="col-lg-4">
					<p class="menu-item" >Grilled Shrimp</p>
					<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Mi tempus imperdiet nulla malesuada pellentesque elit eget.</p>
					<p>$8.99</p>
				</div>
				<div class="col-lg-4">
					<p class="menu-item" >Jalapenos Mi Patio</p>
					<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Mi tempus imperdiet nulla malesuada pellentesque elit eget.</p>
					<p>$6.45</p>
				</div>
				<div class="col-lg-4">
					<p class="menu-item" >Mexican Cerviche</p>
					<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Mi tempus imperdiet nulla malesuada pellentesque elit eget.</p>
					<p>$9.50</p>
				</div>
			</div>
			<div class="row">
				<div class="col-lg-4">
					<p class="menu-item" >Quesadillas Mi Patio</p>
					<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Mi tempus imperdiet nulla malesuada pellentesque elit eget.</p>
					<p>A $8.50 - B $8.50 - C $9.00 - D $10.00</p>
				</div>
				<div class="col-lg-4">
					<p class="menu-item" >Chorizo Fondeaux</p>
					<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Mi tempus imperdiet nulla malesuada pellentesque elit eget.</p>
					<p>$8.25</p>
				</div>
				<div class="col-lg-4">
					<p class="menu-item" >Guacomole</p>
					<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Mi tempus imperdiet nulla malesuada pellentesque elit eget.</p>
					<p>Small $3.90 - Large $7.10</p>
				</div>
			</div>
			<div class="row">
				<div class="col-lg-4">
					<p class="menu-item" >Mexican Chicken Wings</p>
					<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Mi tempus imperdiet nulla malesuada pellentesque elit eget.</p>
					<p>$9.45</p>
				</div>
				<div class="col-lg-4">
					<p class="menu-item" >Taquitos Mi Patio</p>
					<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Mi tempus imperdiet nulla malesuada pellentesque elit eget.</p>
					<p>$8.10</p>
				</div>
				<div class="col-lg-4">
					<p class="menu-item" >Cocktail Shrimp</p>
					<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Mi tempus imperdiet nulla malesuada pellentesque elit eget.</p>
					<p>$8.75</p>
				</div>
			</div>
			<div class="row">
				<div class="col-lg-6">
					<p class="menu-item" >Sampler Mi Patio</p>
					<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Mi tempus imperdiet nulla malesuada pellentesque elit eget.</p>
					<p>$10.99</p>
				</div>
				<div class="col-lg-6">
					<p class="menu-item" >Greenwave Nachos</p>
					<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Mi tempus imperdiet nulla malesuada pellentesque elit eget.</p>
					<p>$8.10 - $9.10</p>
				</div>
			</div>
	</div>
	<!-- Bottom of the page-->
	
    <?php include("includes/footer.php"); ?>
    
</body>
</html>