<!DOCTYPE html>

<html lang="en">
<head>
	<!-- Required meta tags -->
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<!-- Bootstrap CSS -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
	<link rel="stylesheet" href="css/styles.css" type="text/css">
	<link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css?family=Playball" rel="stylesheet"> 
	<title>Mi Patio Mexican Restaurant</title>
</head>
<body>
	
    <?php include("includes/header.php"); ?>
    
	<!-- Center of the Page-->
	<div class="container-fluid">
		<form action=" ">
			<!-- Box with input fields -->
			<div class="panel panel-default">
				<!-- Heading 1 -->
				<div class="panel-heading" id="job-panel-heading">Applicant Data</div>
			
				<!-- Input Fields Under Heading 1 -->
				<div class="panel-body">
					<!-- Reference -->
					<div class="form-group">
						<label for="refer">How Were You Referred To Us:</label>
						<input type="text" class="form-control" placeholder="Employer's Name" id="refer">
					</div>

					<!-- Position -->
					<div class="form-group">
						<label for="position">Position Applied For:</label>
						<input type="text" class="form-control" placeholder="Server/Busboy/etc..." id="position">
					</div>

					<!-- Full Name -->
					<div class="form-group">
						<label for="usr">Full Name:</label>
						<input type="text" class="form-control" placeholder="Name" id="usr">
					</div>

					<!-- Street Address -->
					<div class="form-group">
						<label for="address">Address:</label>
						<input type="text" class="form-control" placeholder="Street Address" id="address">
					</div>
					
					<!-- City -->
					<div class="form-group">
						<label for="city">City:</label>
						<input type="text" class="form-control" placeholder="City" id="city">
					</div>

					<!-- State -->
					<div class="form-group">
						<label for="state">State:</label>
						<select class="form-control input-sm" id="state">
							<option value="AL">Alabama</option>
							<option value="AK">Alaska</option>
							<option value="AZ">Arizona</option>
							<option value="AR">Arkansas</option>
							<option value="CA">California</option>
							<option value="CO">Colorado</option>
							<option value="CT">Connecticut</option>
							<option value="DE">Delaware</option>
							<option value="DC">District Of Columbia</option>
							<option value="FL">Florida</option>
							<option value="GA">Georgia</option>
							<option value="HI">Hawaii</option>
							<option value="ID">Idaho</option>
							<option value="IL">Illinois</option>
							<option value="IN">Indiana</option>
							<option value="IA">Iowa</option>
							<option value="KS">Kansas</option>
							<option value="KY">Kentucky</option>
							<option value="LA">Louisiana</option>
							<option value="ME">Maine</option>
							<option value="MD">Maryland</option>
							<option value="MA">Massachusetts</option>
							<option value="MI">Michigan</option>
							<option value="MN">Minnesota</option>
							<option value="MS">Mississippi</option>
							<option value="MO">Missouri</option>
							<option value="MT">Montana</option>
							<option value="NE">Nebraska</option>
							<option value="NV">Nevada</option>
							<option value="NH">New Hampshire</option>
							<option value="NJ">New Jersey</option>
							<option value="NM">New Mexico</option>
							<option value="NY">New York</option>
							<option value="NC">North Carolina</option>
							<option value="ND">North Dakota</option>
							<option value="OH">Ohio</option>
							<option value="OK">Oklahoma</option>
							<option value="OR">Oregon</option>
							<option value="PA">Pennsylvania</option>
							<option value="RI">Rhode Island</option>
							<option value="SC">South Carolina</option>
							<option value="SD">South Dakota</option>
							<option value="TN">Tennessee</option>
							<option value="TX">Texas</option>
							<option value="UT">Utah</option>
							<option value="VT">Vermont</option>
							<option value="VA">Virginia</option>
							<option value="WA">Washington</option>
							<option value="WV">West Virginia</option>
							<option value="WI">Wisconsin</option>
							<option value="WY">Wyoming</option>
						</select>					
					</div>

					<!-- Zip Code -->
					<div class="form-group">
						<label for="zip">Zip:</label>
						<input type="text" class="form-control" placeholder="Zip Code" id="zip">
					</div>
					
					<!-- Phone Number -->
					<div class="form-group">
						<label for="phone">Phone:</label>
						<input type="tel" class="form-control" placeholder="(000) 000-0000" id="phone">
					</div>
					
					<!-- Email Address -->
					<div class="form-group">
						<label for="email">Email:</label>
						<input type="email" class="form-control" placeholder="Email" id="email">
					</div>
					
					<!-- Starting Date -->
					<div class="form-group">
						<label for="date_start">Date Available To Start:</label>
						<input type="date" class="form-control" id="date_start">
					</div>
					
					<!-- Salary Requirements -->
					<div class="form-group">
						<label for="salary">Salary Requirements:</label>
						<input type="text" class="form-control" placeholder="$00.00" id="salary">
					</div>
					
					<!-- Work Permit -->
					<div class="form-group">
  						<label for="permit">If you are under 18 years of age, can you provide a work permit?</label>
  						<select class="form-control input-sm" id="permit">
    						<option>Yes</option>
    						<option>No</option>
  						</select>
					</div> 
					
					<!-- Explaination 1 -->
					<div class="form-group">
  						<label for="explaination">If no, please explain:</label>
  						<textarea class="form-control" rows="2" id="explaination"></textarea>
					</div>

					<!-- Work For Company -->
					<div class="form-group">
  						<label for="company-work">Have you ever worked for this company?</label>
  						<select class="form-control input-sm" id="company-work">
    						<option>Yes</option>
    						<option>No</option>
  						</select>
					</div> 

					<!-- Explaination 2 -->
					<div class="form-group">
  						<label for="explaination2">If yes, when?</label>
  						<input type="date" class="form-control" id="explaination2">
					</div>

					<!-- Work In US -->
					<div class="form-group">
  						<label for="legal">Are you legally allowed to work in the United States?</label>
  						<select class="form-control input-sm" id="legal">
    						<option>Yes</option>
    						<option>No</option>
  						</select>
					</div> 

					<!-- Type Of Employment -->
					<div class="form-group">
  						<label for="employment-type">Type of employment desired:</label>
  						<select class="form-control input-sm" id="employment-type">
    						<option>Full-Time</option>
    						<option>Part-Time</option>
							<option>Temporary</option>
							<option>Seasonal</option>
  						</select>
					</div> 
				</div>

				<!-- Heading 2 -->
				<div class="panel-heading" id="job-panel-heading">Education History</div>

				<!-- Input Fields under Heading 2 -->
				<div class="panel-body">
					<!-- Name of High School -->
					<div class="form-group">
						<label for="high-school-name">Name of High School:</label>
						<input type="text" class="form-control" placeholder="Name of High School" id="high-school-name">
					</div>

					<!-- Location of High School -->
					<div class="form-group">
						<label for="high-school-location">Location of High School:</label>
						<input type="text" class="form-control" placeholder="Location of High School" id="high-school-location">
					</div>

					<!-- Graduate -->
					<div class="form-group">
  						<label for="graduate">Did you graduate?</label>
  						<select class="form-control input-sm" id="graduate">
    						<option>Yes</option>
    						<option>No</option>
  						</select>
					</div> 

					<!-- Name of College -->
					<div class="form-group">
						<label for="college-name">Name of College:</label>
						<input type="text" class="form-control" placeholder="Name of College" id="college-name">
					</div>

					<!-- Location of College -->
					<div class="form-group">
						<label for="college-location">Location of College:</label>
						<input type="text" class="form-control" placeholder="Location of College" id="college-location">
					</div>

					<!-- Years Attended -->
					<div class="form-group">
						<label for="years">Years Attended:</label>
						<input type="number" class="form-control" placeholder="# of Years Attended" id="years">
					</div>

					<!-- Degrees -->
					<div class="form-group">
						<label for="degree">Degrees Completed:</label>
						<input type="text" class="form-control" placeholder="Degrees" id="degree">
					</div>

					<!-- Studied Subjects -->
					<div class="form-group">
						<label for="subject">Other Subjects Studied:</label>
						<input type="text" class="form-control" placeholder="Subjects" id="subject">
					</div>

					<!-- Trade School -->
					<div class="form-group">
						<label for="trade">Trade, Business or Correspondence School:</label>
						<input type="text" class="form-control" placeholder="Trade School" id="trade">
					</div>

					<!-- Years Attended -->
					<div class="form-group">
						<label for="years">Years Attended:</label>
						<input type="number" class="form-control" placeholder="# of Years Attended" id="years">
					</div>

					<!-- Studied Subjects -->
					<div class="form-group">
						<label for="subject">Subjects Studied:</label>
						<input type="text" class="form-control" placeholder="Subjects" id="subject">
					</div>

					<!-- Graduate -->
					<div class="form-group">
  						<label for="graduate">Did you graduate?</label>
  						<select class="form-control input-sm" id="graduate">
    						<option>Yes</option>
    						<option>No</option>
  						</select>
					</div> 
				</div>

				<!-- Heading 3 -->
				<div class="panel-heading" id="job-panel-heading">Summarize Your Special Skills or Qualifications</div>

				<!-- Input Field Under Heading 3 -->
				<div class="panel-body">
					<div class="form-group">
  						<label for="skills">Skills/Qualifications</label>
  						<textarea class="form-control" rows="8" id="skills"></textarea>
					</div>

					<!-- Submit Button -->
					<div class="form-group">
						<div class="col-lg-12 text-center">
							<button type="button" class="btn btn-info">
      							<span class="glyphicon glyphicon-send"></span> Submit
    						</button>
						</div>
					</div> 
				</div>
			</div>
		</form>
	</div>
	
	<!-- Bottom of the page-->
	<?php include("includes/footer.php"); ?>
    
</body>
</html>