<!DOCTYPE html>

<html lang="en">
<head>
	<!-- Required meta tags -->
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	
	<!-- Bootstrap CSS -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
	<link rel="stylesheet" href="css/styles.css" type="text/css">
	
	<!-- Fonts -->
	<link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css?family=Dancing+Script" rel="stylesheet"> 
	<link href="https://fonts.googleapis.com/css?family=Playball" rel="stylesheet"> 
	<!--<link href="https://fonts.googleapis.com/css?family=Open+Sans+Condensed:300" rel="stylesheet"> --> 
	
	<!-- Tab Image -->
	<link rel="icon" type="image/png" href="public/img/favicon.png">
	
	<!-- JQuery -->
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	
	<title>Mi Patio Mexican Restaurant</title>
</head>
<body>
	<!-- Top of the Page -->
    <?php include("includes/header.php"); ?>
    
	<!-- Center of the Page-->
	<!-- Page content -->
		<div id="main">
			<div class="container-fluid text-center">
				<div class="row">
					<div class="col-lg-12" id="special-page">
						<h2 class="display-1">Specials</h2>
					</div>
				</div>
				
				<div class="row">
					<!-- Side bar -->
					<div class="col-lg-2">
						<div class="well" id="special-page">
							<header>
								<h2 class="display-1">Days</h2>
							</header>
							<ul class="nav nav-pills">
								<li><a href="#monday">Monday</a></li>
								<li><a href="#tuesday">Tuesday</a></li>
								<li><a href="#wednesday">Wednesday</a></li>
								<li><a href="#monday">Thursday</a></li>
								<li><a href="#monday">Friday</a></li>
								<li><a href="#saturday">Saturday</a></li>
								<li><a href=" ">Sunday</a></li>
							</ul>
						</div>	
					</div>
					
					<!-- Center Content -->
					<div class="col-lg-8" id="special-page">
						<!-- Monday-Friday -->
						<h2 class="display-2" id="monday">Monday-Friday</h2>
							
						<!-- Free sweet tea -->
						<img class="img-responsive" src="img/sweet_tea2.jpg" alt="Sweet tea" />
						<div class="caption">
							<p>Enjoy our cold, refreshing sweet/unsweet tea for free with your lunch</p>
						</div>	
							
						<!-- Happy Hour -->
						<img class="img-responsive" src="img/strawberry_margarita2.jpg" alt="Strawberry margarita" />
						<div class="caption">
							<p>Small house and small strawberry margaritas for $3.50 from 2-6 PM!</p>
						</div>
						
						<!-- Taco Tuesday -->
						<h2 class="display-2" id="tuesday">Taco Tuesday</h2>
							
						<!-- Tacos -->
						<img class="img-responsive" src="img/tacos_pastor2.jpg" alt="Tacos al Pastor" />
						<div class="caption">
							<p>Come eat our wide selection of delicious tacos that range from 
							shredded chicken to barbacoa. Prices range from only $0.99 to $1.99</p>
						</div>
							
						<!-- Taco Salads -->
						<img class="img-responsive" src="img/taco_salad2.jpg" alt="Taco salad" />
						<div class="caption">
							<p>Beef and chicken taco salad for $5.99</p>
							<br />
							<p>Steak and grilled chicken taco salad for $6.99</p>
							<br />
							<p>Shrimp taco salad for $7.99</p> 
						</div>	
						
						<!-- Wednesday -->
						<h2 class="display-2" id="wednesday">Wednesday</h2>
							
						<!-- Steak fajitas -->
						<img class="img-responsive" src="img/steak_fajitas2.jpg" alt="Steak fajitas" />
						<div class="caption">
							<p>Have our mouthwatering chicken or steak fajitas for $9.99</p>
						</div>
							
						<!-- Small house margaritas -->
						<img class="img-responsive" src="img/small_margarita2.jpg" alt="Small margarita" />
						<div class="caption">
							<p>Small house margaritas for $3.50</p>
						</div>
							
						<!-- Wednesday and Saturday -->
						<h2 class="display-2" id="saturday">Wednesday and Saturday</h2>
							
						<!-- Buy 1 get one 1 free -->
						<img class="img-responsive" src="img/large_margarita2.jpg" alt="Large margarita" />
						<div class="caption">
							<p>Buy 1 large margarita and get a small one for FREE!</p>
						</div>	
					</div>

					<!-- Lent Menu -->
					<div class="col-lg-2">
						<div class="panel panel-default" id="panel">
  							
							<!-- Header -->
							<div class="panel-header">
								<h1 id="lent">Lent</h1>
							</div>
							
							<!-- Content -->
							<div class="panel-body">
								<p>Lorem ipsum dolor sit amet</p>
							</div>
								
							<!-- Menu Button -->
							<div class="panel-footer" id="panel">
								<button type="button" class="btn btn-success btn-sm">
    								<span class="glyphicon glyphicon-file"></span> View Lenten Menu
  								</button> 
							</div>	
						</div>
					</div>
				</div>
			</div>
		</div>
	
		<!-- Bottom of the page-->
	<?php include("includes/footer.php"); ?>
    
</body>
</html>