<!DOCTYPE html>

<html lang="en">
<head>
	<!-- Required meta tags -->
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<!-- Bootstrap CSS -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
	<link rel="stylesheet" href="css/styles.css" type="text/css">
	<link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet">
	<title>Mi Patio Mexican Restaurant</title>
</head>
<body>
	
    <?php include("includes/header.php"); ?>
    
	<!-- Center of the Page-->
	<div class="menu-pages">
		<h1>Lunch</h1>
			<div class="row">
				<div class="col-lg-6">
					<p class="menu-item" >Light Side</p>
					<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Mi tempus imperdiet nulla malesuada pellentesque elit eget.</p>
					<p>$9.00 - $10.00 - $11.25</p>
				</div>
				<div class="col-lg-6">
					<p class="menu-item" >Tortilla Soup</p>
					<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Mi tempus imperdiet nulla malesuada pellentesque elit eget.</p>
					<p>$9.00</p>
				</div>
			</div>
			<h2>Fajitas</h2>
			<div class="row">
				<div class="col-lg-4">
					<p class="menu-item" >Mushroom Fajitas</p>
					<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Mi tempus imperdiet nulla malesuada pellentesque elit eget.</p>
					<p>$10.00</p>
				</div>
				<div class="col-lg-4">
					<p class="menu-item" >Mexican Fajitas</p>
					<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Mi tempus imperdiet nulla malesuada pellentesque elit eget.</p>
					<p>$10.75</p>
				</div>
				<div class="col-lg-4">
					<p class="menu-item" >Shrimp Fajitas</p>
					<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Mi tempus imperdiet nulla malesuada pellentesque elit eget.</p>
					<p>$12.50</p>
				</div>
			</div>
			<div class="row">
				<div class="col-lg-4">
					<p class="menu-item" >Steak Fajitas</p>
					<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Mi tempus imperdiet nulla malesuada pellentesque elit eget.</p>
					<p>$10.75</p>
				</div>
				<div class="col-lg-4">
					<p class="menu-item" >Chicken Fajitas</p>
					<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Mi tempus imperdiet nulla malesuada pellentesque elit eget.</p>
					<p>$10.75</p>
				</div>
				<div class="col-lg-4">
					<p class="menu-item" >Chicken and Steak Fajitas</p>
					<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Mi tempus imperdiet nulla malesuada pellentesque elit eget.</p>
					<p>$11.25</p>
				</div>
			</div>
			<div class="row">
				<div class="col-lg-4">
				</div>
				<div class="col-lg-4">
					<p class="menu-item" >Chicken, Steak, and Shrimp Fajitas</p>
					<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Mi tempus imperdiet nulla malesuada pellentesque elit eget.</p>
					<p>$12.50</p>
				</div>
				<div class="col-lg-4">
				</div>
			</div>
			<h2>Salads</h2>
			<div class="row">
				<div class="col-lg-4">
					<p class="menu-item" >Caesar Salad</p>
					<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Mi tempus imperdiet nulla malesuada pellentesque elit eget.</p>
					<p>$6.00 - $8.50 - $9.75</p>
				</div>
				<div class="col-lg-4">
					<p class="menu-item" >Fajita Taco Salad</p>
					<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Mi tempus imperdiet nulla malesuada pellentesque elit eget.</p>
					<p>$9.95 - $11.25</p>
				</div>
				<div class="col-lg-4">
					<p class="menu-item" >Taco Salad</p>
					<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Mi tempus imperdiet nulla malesuada pellentesque elit eget.</p>
					<p>$6.00 - $7.99 - $9.15 - $10.15</p>
				</div>
			</div>
			<div class="row">
				<div class="col-lg-6">
					<p class="menu-item" >Mesquite Salad</p>
					<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Mi tempus imperdiet nulla malesuada pellentesque elit eget.</p>
					<p>$6.00 - $8.50 - $9.75</p>
				</div>
				<div class="col-lg-6">
					<p class="menu-item" >Guacamole Salad</p>
					<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Mi tempus imperdiet nulla malesuada pellentesque elit eget.</p>
					<p>$4.50</p>
				</div>
			</div>
			<h2>Entrées</h2>
			<div class="row">
				<div class="col-lg-4">
					<p class="menu-item" >House Special</p>
					<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Mi tempus imperdiet nulla malesuada pellentesque elit eget.</p>
					<p>$9.10</p>
				</div>
				<div class="col-lg-4">
					<p class="menu-item" >La Bandera</p>
					<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Mi tempus imperdiet nulla malesuada pellentesque elit eget.</p>
					<p>$8.10</p>
				</div>
				<div class="col-lg-4">
					<p class="menu-item" >La Rancherita</p>
					<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Mi tempus imperdiet nulla malesuada pellentesque elit eget.</p>
					<p>$8.10</p>
				</div>
			</div>
			<div class="row">
				<div class="col-lg-4">
					<p class="menu-item" >El Ranchero</p>
					<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Mi tempus imperdiet nulla malesuada pellentesque elit eget.</p>
					<p>$9.99 - Shrimp $10.99</p>
				</div>
				<div class="col-lg-4">
					<p class="menu-item" >El Estudiante</p>
					<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Mi tempus imperdiet nulla malesuada pellentesque elit eget.</p>
					<p>$8.10</p>
				</div>
				<div class="col-lg-4">
					<p class="menu-item" >Wheat Burrito</p>
					<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Mi tempus imperdiet nulla malesuada pellentesque elit eget.</p>
					<p>$9.10</p>
				</div>
			</div>
			<div class="row">
				<div class="col-lg-4">
					<p class="menu-item" >Burrito de Pollo</p>
					<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Mi tempus imperdiet nulla malesuada pellentesque elit eget.</p>
					<p>$8.10</p>
				</div>
				<div class="col-lg-4">
					<p class="menu-item" >Burrito Supreme</p>
					<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Mi tempus imperdiet nulla malesuada pellentesque elit eget.</p>
					<p>$9.50 - $10.50</p>
				</div>
				<div class="col-lg-4">
					<p class="menu-item" >Speedy Gonzales</p>
					<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Mi tempus imperdiet nulla malesuada pellentesque elit eget.</p>
					<p>$8.10</p>
				</div>
			</div>
			<div class="row">
				<div class="col-lg-4">
					<p class="menu-item" >Taquitos Mexicanos</p>
					<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Mi tempus imperdiet nulla malesuada pellentesque elit eget.</p>
					<p>$8.10</p>
				</div>
				<div class="col-lg-4">
					<p class="menu-item" >El Taquito</p>
					<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Mi tempus imperdiet nulla malesuada pellentesque elit eget.</p>
					<p>$9.10</p>
				</div>
				<div class="col-lg-4">
					<p class="menu-item" >Tamal Mexicano</p>
					<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Mi tempus imperdiet nulla malesuada pellentesque elit eget.</p>
					<p>$9.10 - Shrimp $10.10</p>
				</div>
			</div>
			<div class="row">
				<div class="col-lg-6">
					<p class="menu-item" >Chile Costeno</p>
					<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Mi tempus imperdiet nulla malesuada pellentesque elit eget.</p>
					<p>$10.10 - Shrimp $11.10</p>
				</div>
				<div class="col-lg-6">
					<p class="menu-item" >Chimichanga</p>
					<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Mi tempus imperdiet nulla malesuada pellentesque elit eget.</p>
					<p>$9.50 - $10.50 - $11.00</p>
				</div>
			</div>
			<h2>Quesadillas</h2>
			<div class="row">
				<div class="col-lg-4">
					<p class="menu-item" >Chicken Quesadilla Lunch</p>
					<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Mi tempus imperdiet nulla malesuada pellentesque elit eget.</p>
					<p>$8.00</p>
				</div>
				<div class="col-lg-4">
					<p class="menu-item" >Steak Quesadilla Lunch</p>
					<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Mi tempus imperdiet nulla malesuada pellentesque elit eget.</p>
					<p>$9.00</p>
				</div>
				<div class="col-lg-4">
					<p class="menu-item" >Shrimp Quesadilla Lunch</p>
					<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Mi tempus imperdiet nulla malesuada pellentesque elit eget.</p>
					<p>$10.00</p>
				</div>
			</div>
			<div class="row">
				<div class="col-lg-4">
					<p class="menu-item" >Chicken Quesadilla</p>
					<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Mi tempus imperdiet nulla malesuada pellentesque elit eget.</p>
					<p>$6.75</p>
				</div>
				<div class="col-lg-4">
					<p class="menu-item" >Steak Quesadilla</p>
					<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Mi tempus imperdiet nulla malesuada pellentesque elit eget.</p>
					<p>$7.75</p>
				</div>
				<div class="col-lg-4">
					<p class="menu-item" >Shrimp Quesadilla</p>
					<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Mi tempus imperdiet nulla malesuada pellentesque elit eget.</p>
					<p>$8.75</p>
				</div>
			</div>
			<div class="row">
				<div class="col-lg-6">
					<p class="menu-item" >Huevos Mexicanos</p>
					<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Mi tempus imperdiet nulla malesuada pellentesque elit eget.</p>
					<p>$11.50</p>
				</div>
				<div class="col-lg-6">
					<p class="menu-item" >Chorizo and Scrambled Eggs</p>
					<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Mi tempus imperdiet nulla malesuada pellentesque elit eget.</p>
					<p>$10.75</p>
				</div>
			</div>
	</div>
	<!-- Bottom of the page-->
	
    <?php include("includes/footer.php"); ?>
    
</body>
</html>