<!DOCTYPE html>

<html lang="en">
<head>
	<!-- Required meta tags -->
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<!-- Bootstrap CSS -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
	<link rel="stylesheet" href="css/styles.css" type="text/css">
	<link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet">
	<title>Mi Patio Mexican Restaurant</title>
</head>
<body>
	
    <?php include("includes/header.php"); ?>
    
	<!-- Center of the Page-->
	
	<!-- First row of pics -->
	<div class="gallery-page">
	<div class="row">
  		<div class="col-md-4">
    		<div class="thumbnail">
        		<img class="img-responsive" src="img/salsa-1670402_1920.png" alt="Pic 1" style="width:100%">
    		</div>
  		</div>
  		<div class="col-md-4">
    		<div class="thumbnail">
        		<img class="img-responsive" src="img/tacos-245241_1920.png" alt="Pic 2" style="width:100%">
    		</div>
  		</div>
  		<div class="col-md-4">
    		<div class="thumbnail">
      			<img class="img-responsive" src="img/tacos-1613795_1280.jpg" alt="Pic 3" style="width:100%">
    		</div>
  		</div>
	</div>
	
	<!-- Second row of pics -->
	<div class="row">
		<div class="col-md-4">
    		<div class="thumbnail">
        		<img class="img-responsive" src="img/salsa-1670402_1920.png" alt="Pic 1" style="width:100%">
    		</div>
  		</div>
  		<div class="col-md-4">
    		<div class="thumbnail">
        		<img class="img-responsive" src="img/tacos-245241_1920.png" alt="Pic 2" style="width:100%">
    		</div>
  		</div>
  		<div class="col-md-4">
    		<div class="thumbnail">
      			<img class="img-responsive" src="img/tacos-1613795_1280.jpg" alt="Pic 3" style="width:100%">
    		</div>
  		</div>
	</div>
	</div>
	
	<!-- Bottom of the page-->
	<?php include("includes/footer.php"); ?>
    
</body>
</html>