<!DOCTYPE html>

<html lang="en">
<head>
	<!-- Required meta tags -->
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<!-- Bootstrap CSS -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
	<link rel="stylesheet" href="css/styles.css" type="text/css">
	<link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet">
	<title>Mi Patio Mexican Restaurant</title>
</head>
<body>
	
    <?php include("includes/header.php"); ?>
    
	<!-- Center of the Page-->
	<div class="menu-pages">
		<h1>Soups</h1>
			<div class="row">
				<div class="col-lg-4">
					<p class="menu-item" >Spicy Tortilla Soup</p>
					<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Mi tempus imperdiet nulla malesuada pellentesque elit eget.</p>
					<p>Small $3.50 - Large $4.99</p>
				</div>
				<div class="col-lg-4">
					<p class="menu-item" >Home Style Shrimp Soup</p>
					<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Mi tempus imperdiet nulla malesuada pellentesque elit eget.</p>
					<p>$8.00</p>
				</div>
				<div class="col-lg-4">
					<p class="menu-item" >Mexican Cowboy Bean Soup</p>
					<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Mi tempus imperdiet nulla malesuada pellentesque elit eget.</p>
					<p>Small $3.50 - Large $4.99</p>
				</div>
			</div>
			<div class="row">
				<div class="col-lg-4">
				</div>
				<div class="col-lg-4">
					<p class="menu-item" >Mi Patio Speciality Soup</p>
					<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Mi tempus imperdiet nulla malesuada pellentesque elit eget.</p>
					<p>Small $4.25 - Large $6.50</p>
				</div>
				<div class="col-lg-4">
				</div>
			</div>
	</div>
	<!-- Bottom of the page-->
	
    <?php include("includes/footer.php"); ?>
    
</body>
</html>