<!DOCTYPE html>

<html lang="en">
<head>
	<!-- Required meta tags -->
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<!-- Bootstrap CSS -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
	<link rel="stylesheet" href="css/styles.css" type="text/css">
	<link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet">
	<title>Mi Patio Mexican Restaurant</title>
</head>
<body>
	
    <?php include("includes/header.php"); ?>
    
	<!-- Center of the Page-->
	<div class="contact-page">
		<div class="row">
			<div class="col">
				<h1>Contact Information</h1>
				<p>Mi Patio Mexican Restaurant</p>
				<p><a href="tel:985-370-0006">(985) 370-0006</a></p>
				<p>120 N. Barronne Street</p>
				<p>Ponchatoula, LA, 70454</p>
                <br />
				<h1>Hours of Operation</h1>
				<p>Mon-Thurs: 11:00 AM - 10:00 PM</p>
				<p>Fri & Sat: 11:00 AM - 10:30 PM</p>
				<p>Sun: 11:00 AM - 9:00 PM</p>
			</div>
			<div class="col">
				<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3439.8119916562737!2d-90.43482528501032!3d30.44143118173964!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x86273ca202f9f10b%3A0xe5a6defa2b761409!2sMi+Patio+Mexican+Restaurant!5e0!3m2!1sen!2sus!4v1520312172849" width="600" height="450" frameborder="0" style="border:0" id="gmap" allowfullscreen></iframe>
			</div>
		</div>
	</div>
	<!-- Bottom of the page-->
	
    <?php include("includes/footer.php"); ?>
    
</body>
</html>