<?php 
/*
	if($_SERVER["REQUEST_METHOD"] == "POST") {
		$name = test_input($_POST["name"]);	
		
		$guests = test_input($_POST["guests"]);
		
		$phone = test_input($_POST["phone"]);
		
		$email = test_input($_POST["email"]);
		
		$date = test_input($_POST["date"]);
		
		$time = test_input($_POST["time"]);
		
		$message_body = "";
		unset($_POST['submit']);
		foreach ($_POST as $key => $value){
			$message_body .= "$key: $value\n";
		}
		
		$to = 'email-address';
		$subject = 'test';
		if (mail($to, $subject, $message_body)){
			$success = "Message Sent";
			$name = $guests = $phone = $email = $date = $time = '';
		}
	} 
	
	function test_input($data) {
		$data = trim($data);
		$data = stripslashes($data);
		$data = htmlspecialchars($data);
		return $data;
	}
*/
?>