<!DOCTYPE html>

<html lang="en">
<head>
	<!-- Required meta tags -->
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<!-- Bootstrap CSS -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
	<link rel="stylesheet" href="css/styles.css" type="text/css">
	<link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet">
	<title>Mi Patio Mexican Restaurant</title>
</head>
<body>
	
    <?php include("includes/header.php"); ?>
    
	<!-- Center of the Page-->
	<div class="menu-pages">
		<h1>A La Carte</h1>
			<div class="row">
				<div class="col-lg-4">
					<p class="menu-item" >Beans</p>
					<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Mi tempus imperdiet nulla malesuada pellentesque elit eget.</p>
					<p>$2.50</p>
				</div>
				<div class="col-lg-4">
					<p class="menu-item" >Rice</p>
					<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Mi tempus imperdiet nulla malesuada pellentesque elit eget.</p>
					<p>$2.50</p>
				</div>
				<div class="col-lg-4">
					<p class="menu-item" >Taco</p>
					<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Mi tempus imperdiet nulla malesuada pellentesque elit eget.</p>
					<p>A $2.00 - B $2.10 - C $3.25</p>
				</div>
			</div>
			<div class="row">
				<div class="col-lg-4">
					<p class="menu-item" >Enchilada</p>
					<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Mi tempus imperdiet nulla malesuada pellentesque elit eget.</p>
					<p>A $2.25 - B $3.25</p>
				</div>
				<div class="col-lg-4">
					<p class="menu-item" >Steak Burrito</p>
					<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Mi tempus imperdiet nulla malesuada pellentesque elit eget.</p>
					<p>$6.50</p>
				</div>
				<div class="col-lg-4">
					<p class="menu-item" >Beef and Bean Burrito</p>
					<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Mi tempus imperdiet nulla malesuada pellentesque elit eget.</p>
					<p>$4.50</p>
				</div>
			</div>
			<div class="row">
				<div class="col-lg-4">
					<p class="menu-item" >Steak and Bean Burrito</p>
					<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Mi tempus imperdiet nulla malesuada pellentesque elit eget.</p>
					<p>$5.50</p>
				</div>
				<div class="col-lg-4">
					<p class="menu-item" >Taquito Mexicano</p>
					<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Mi tempus imperdiet nulla malesuada pellentesque elit eget.</p>
					<p>$2.10</p>
				</div>
				<div class="col-lg-4">
					<p class="menu-item" >Cheese Chile Relleno</p>
					<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Mi tempus imperdiet nulla malesuada pellentesque elit eget.</p>
					<p>$4.00</p>
				</div>
			</div>
			<div class="row">
				<div class="col-lg-6">
					<p class="menu-item" >Shrimp Chile Relleno</p>
					<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Mi tempus imperdiet nulla malesuada pellentesque elit eget.</p>
					<p>$5.00</p>
				</div>
				<div class="col-lg-6">
					<p class="menu-item" >Tostada</p>
					<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Mi tempus imperdiet nulla malesuada pellentesque elit eget.</p>
					<p>$3.75</p>
				</div>
			</div>
	</div>

	<!-- Bottom of the page-->
	
    <?php include("includes/footer.php"); ?>
    
</body>
</html>