<html>
    <head>
    <!-- Required meta tags -->
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<!-- Bootstrap CSS -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
	<link rel="stylesheet" href="/css/styles.css" type="text/css">
	<link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet">
	<!-- Latest compiled and minified CSS -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
	<!-- Optional theme -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
<!--    <link rel="shortcut icon" href="public/img/favicon.ico" type="image/x-icon"> -->
    
    <title>Mi Patio Mexican Restaurant</title>
    </head>
    <body>
	<!-- Top of the page-->
    
<?php include("includes/header.php"); ?>
        
	<!-- Center of the page -->
	<!--
<div class="home-middle">
        <img src="img/tacos-245241_1920.png" />
    </div>
-->
	<div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
		<div class="carousel-inner">
			<div class="carousel-item active">
				<img class="d-block w-100" src="img/tacos-245241_1920-(1).png" alt="First slide">
    		</div>
			<div class="carousel-item">
				<img class="d-block w-100" src="img/grilled-pineapple-pork-burrito-2944562_1920.png" alt="Second slide">
    		</div>
			<div class="carousel-item">
				<img class="d-block w-100" src="img/tacos-1904921_1920.png" alt="Third slide">
    		</div>
    		<div class="carousel-item">
				<img class="d-block w-100" src="img/mango-catfish-taco-2944558_1920.png" alt="Third slide">
    		</div>
  		</div>
  		<a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
  			<span class="carousel-control-prev-icon" aria-hidden="true"></span>
  			<span class="sr-only">Previous</span>
  		</a>
  		<a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
  			<span class="carousel-control-next-icon" aria-hidden="true"></span>
  			<span class="sr-only">Next</span>
  		</a>
	</div>
    <div class="box">
        <div class="row">
            <div class="col-lg-4">
                <a href="/appetizers"><img src="img/salsa-1670402_1920.png" /></a>
                <p class="menu-links">
                    <a href="/appetizers">Appetizers</a>
                </p>
            </div>
            <div class="col-lg-4">
                <a href="/lunch"><img src="img/tacos-1613795_1280.jpg" /></a>
                <p class="menu-links">
                    <a href="/lunch">Lunch</a>
                </p>
            </div>
            <div class="col-lg-4">
                <a href="/dinner"><img src="img/mexican-2456038_1280.jpg" /></a>
                <p class="menu-links">
                    <a href="/dinner">Dinner</a>
                </p>
            </div>
        </div>
    </div>

<!--
<div class="page-header">
    <h1>Congratulations!</h1>
</div>

<p>You're now flying with Phalcon. Great things are about to happen!</p>

<p>This page is located at <code>views/index/index.phtml</code></p>

<a href="/menu">Menu</a>

<a href="/menu">Events</a>

<a href="/menu">About Us</a>
-->
        
<?php include("includes/footer.php"); ?>

	<!-- Optional JavaScript -->
	<!-- jQuery first, then Popper.js, then Bootstrap JS -->
	<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    
</html>